version: "3.8"

services:
  app:
    build:
      args:
        user: 1000
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: calambre
    container_name: calambre-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/xdebug_error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - calambre
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: postgres
    container_name: calambre-db
    restart: unless-stopped
    user: "${POSTGRES_UID}:${POSTGRES_GID}"`
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calambre_db
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - calambre

  nginx:
    image: nginx:alpine
    container_name: calambre-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - calambre


  mailhog:
    image: mailhog/mailhog
    container_name: calambre-mail
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - calambre

  redis:
    image: "redis:alpine"
    command: redis-server
    container_name: calambre-queue
    expose:
      - "6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - calambre


networks:
  calambre:
    driver: bridge

volumes:
  redis-data:
  redis-conf: